## Project 1: Data Cleaning & Preparation

In [8]:
import pandas as pd

df = pd.read_excel('Dataset for Data Analytics.xlsx')

df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

### Dataset Overview

In [ ]:
df.shape

(1200, 14)

### Data Validation Check

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   datetime64[ns]
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 131.4+ KB

###Finding:
All data types were correctly assigned.

### Missing Values Check

In [9]:
df.isnull().sum()

OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

###Finding:
CouponCode has 309 missing values.
The other columns contain no missing values.

### Filling nulls in CouponCode Column

In [10]:
df['CouponCode'] = df['CouponCode'].fillna('NO_COUPON')

In [11]:
df.isnull().sum()

OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

###Finding:
No missing values found

### Duplicates Check

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
df['OrderID'].duplicated().sum()

np.int64(0)

###Finding:
No duplicate rows found.
No duplicate OrderIDs found.

### Category Consistency Check

In [ ]:
df['PaymentMethod'].unique()

array(['Debit Card', 'Online', 'Credit Card', 'Gift Card', 'Cash'],
      dtype=object)

In [ ]:
df['OrderStatus'].unique()

array(['Shipped', 'Cancelled', 'Returned', 'Delivered', 'Pending'],
      dtype=object)

In [ ]:
df['ReferralSource'].unique()

array(['Instagram', 'Referral', 'Email', 'Facebook', 'Google'],
      dtype=object)

### Finding:
All categories are consistent

### Whitespace Check

In [5]:
text_cols = df.select_dtypes(include='object').columns

for col in text_cols:
    count = (df[col] != df[col].str.strip()).sum()
    print(f"{col}: {count}")

OrderID: 0
CustomerID: 0
Product: 0
ShippingAddress: 0
PaymentMethod: 0
OrderStatus: 0
TrackingNumber: 0
CouponCode: 0
ReferralSource: 0

###Finding:
No white space found.

### Verify total price

In [19]:
df[
    round(df['Quantity'] * df['UnitPrice'], 2)
    != round(df['TotalPrice'], 2)
]

Empty DataFrame
Columns: [OrderID, Date, CustomerID, Product, Quantity, UnitPrice, ShippingAddress, PaymentMethod, OrderStatus, TrackingNumber, ItemsInCart, CouponCode, ReferralSource, TotalPrice]
Index: []

###Finding:
The TotalPrice calculations are correct

### Negative or Invalid numerical number Check

In [ ]:
df[df['Quantity'] <= 0]

Empty DataFrame
Columns: [OrderID, Date, CustomerID, Product, Quantity, UnitPrice, ShippingAddress, PaymentMethod, OrderStatus, TrackingNumber, ItemsInCart, CouponCode, ReferralSource, TotalPrice]
Index: []

In [ ]:
df[df['UnitPrice'] <= 0]

Empty DataFrame
Columns: [OrderID, Date, CustomerID, Product, Quantity, UnitPrice, ShippingAddress, PaymentMethod, OrderStatus, TrackingNumber, ItemsInCart, CouponCode, ReferralSource, TotalPrice]
Index: []

###Finding:
No negative or invalid number found

### Business Logic Check

In [ ]:
df[df['ItemsInCart'] < df['Quantity']]

Empty DataFrame
Columns: [OrderID, Date, CustomerID, Product, Quantity, UnitPrice, ShippingAddress, PaymentMethod, OrderStatus, TrackingNumber, ItemsInCart, CouponCode, ReferralSource, TotalPrice]
Index: []

### Finding:
No ItemsIncart is less than Quantity

In [6]:
df.to_excel('cleaned_dataset.xlsx', index=False)

In [7]:
from google.colab import files
files.download('cleaned_dataset.xlsx')